FORMAT: 1A
HOST: http://private-d1080-burnhamsprice.apiary-mock.com

# burnhamsprice

Price service to get product prices

## Champange [/v3/price/TPNC/250373296/]

### GET [GET]

+ Response 200 (application/json)

        {"tpnb":"052182793","pricingDate":"2015-12-29","pricingLocation":{"locType":"national","locRef":"UK"},"variants":[{"tpnc":"250373296","currency":"GBP","sellingUOM":"EA","regPrice":"25.00","promoPrice":"15.00","clrPrice":null,"authPrice":"15.00","clearances":[]}],"promotions":[{"offerId":"A31881146","offerName":"N1  NCLAS FUILTTE BRT CHMP 75CL ONLY £15","effectiveDate":"2015-12-14","endDate":"2016-01-02","customerFriendlyDescription1":" Only £15.00","customerFriendlyDescription2":"NICOLAS FEUILLATTE BRUT CHAMPAGNE 75CL"}]}
