FORMAT: 1A
HOST: http://private-d1080-burnhamsprice.apiary-mock.com

# burnhamsprice

Price service to get product prices

## Champange [/v3/price/tpnc/250373296?unitSellingInfo=true]

### GET [GET]

+ Response 200 (application/json)

        {"tpnb":"052182793","pricingDate":"2015-12-30","pricingLocation":{"locType":"national","locRef":"UK"},"variants":[{"tpnc":"250373296","currency":"GBP","sellingUOM":"EA","regPrice":"25.00","promoPrice":"15.00","clrPrice":null,"authPrice":"15.00","clearances":[],"alternateSellingInfo":[],"unitSellingInfo":[{"unitSellPrice":"15.00","unitSellUOM":"75cl"}]}],"promotions":[{"offerId":"A31881146","offerName":"N1  NCLAS FUILTTE BRT CHMP 75CL ONLY £15","effectiveDate":"2015-12-14","endDate":"2016-01-02","customerFriendlyDescription1":" Only £15.00","customerFriendlyDescription2":"NICOLAS FEUILLATTEBRUT CHAMPAGNE75CL"}]}


## Potatoes [/v3/price/tpnc/253558183?unitSellingInfo=true]

### GET [GET]

+ Response 200 (application/json)

        {"tpnb":"050503464","pricingDate":"2015-12-30","pricingLocation":{"locType":"national","locRef":"UK"},"variants":[{"tpnc":"253558183","currency":"GBP","sellingUOM":"KG","regPrice":"1.00","promoPrice":null,"clrPrice":null,"authPrice":"1.00","clearances":[],"alternateSellingInfo":[{"sellingPrice":"0.30","sellingUOM":"each"}],"unitSellingInfo":[{"unitSellPrice":"1.00","unitSellUOM":"kg"},{"unitSellPrice":"0.45","unitSellUOM":"lb"}]}],"promotions":[]}
        

## Dreamies Mix Beef And Cheese 2 for £2 [/v3/price/tpnc/272384261?unitSellingInfo=true]

### GET [GET]

+ Response 200 (application/json)

        {"tpnb":"071166778","pricingDate":"2015-12-30","pricingLocation":{"locType":"national","locRef":"UK"},"variants":[{"tpnc":"272384261","currency":"GBP","sellingUOM":"EA","regPrice":"1.19","promoPrice":null,"clrPrice":null,"authPrice":"1.19","clearances":[],"alternateSellingInfo":[],"unitSellingInfo":[]}],"promotions":[{"offerId":"A31862557","offerName":"N1 DRM,FLX,BKE,ADVR CAT/DOG TRT 2 FOR £2","effectiveDate":"2015-12-02","endDate":"2016-01-03","customerFriendlyDescription1":" Any 2 for £2.00","customerFriendlyDescription2":"SELECTEDDREAMIES,FELIX, BAKERSOR ADVENTUROSCAT OR DOG TREATS45G-270G"}]}
        

## Adventuros Strips 2 for £2 [/v3/price/tpnc/286782730?unitSellingInfo=true]

### GET [GET]

+ Response 200 (application/json)

        {"tpnb":"078239578","pricingDate":"2015-12-30","pricingLocation":{"locType":"national","locRef":"UK"},"variants":[{"tpnc":"286782730","currency":"GBP","sellingUOM":"EA","regPrice":"1.30","promoPrice":null,"clrPrice":null,"authPrice":"1.30","clearances":[],"alternateSellingInfo":[],"unitSellingInfo":[]}],"promotions":[{"offerId":"A31862557","offerName":"N1 DRM,FLX,BKE,ADVR CAT/DOG TRT 2 FOR £2","effectiveDate":"2015-12-02","endDate":"2016-01-03","customerFriendlyDescription1":" Any 2 for £2.00","customerFriendlyDescription2":"SELECTEDDREAMIES,FELIX, BAKERSOR ADVENTUROSCAT OR DOG TREATS45G-270G"}]}
        
        